spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${PROD_DATABASE_PORT}/${PROD_DATABASE_NAME}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI}

